#!/usr/bin/bash
# A bash script that finds how many terminals has a user logged in

#Taking input from user
echo 'Enter LOGNAME or UID'
read input

#Checking if input is a UID or a LOGNAME
if [[ $input ]] && [ $input -eq $input 2>/dev/null ]

	#if input is UID
	then
		echo 'Number of terminals are '
		cat etc/passwd | grep $input -c

	#if input is LOGNAME
	else
		cat etc/passwd>userlist
		echo 'Number of terminals are '
		grep -c $input userlist
fi
