#!/usr/bin/bash
#A script that uses while and if

index=0

while [ $index -le 10 ]
do
	if [ $index -eq 5 ]
	then
		echo "Senoir DevOps Engineer"
		echo "Keith Koki"
	else
		echo "Senior DevOps Engineer"
	fi
	index=$((index+1))
	sleep 0.9
done	
