#!/usr/bin/bash
#A bash script that prints badluck at 4th, goodluck at 8th and rest DevOps.

index=0

while [ $index -lt 10 ]
do
	if [ $index -eq 3 ]
	then
		echo "bad luck"
	elif [ $index -eq 7 ]
	then
		echo "good luck"
	else
		echo "DevOps Engineer"
	fi
	index=$((index+1))
	sleep 0.9
done
