#!/usr/bin/bash
#A shell script that prints the time for 12 hours and 59 minutes:
	#displays hours from 0 to 12
	#displays minutes from 1 to 59
#Must use while loop...(for and until are forbidden)

hour=0

while [ $hour -lt 13 ]
do 
	echo "Hour: $hour"
	
	minute=1
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done

	((hour++))
done
