#!/usr/bin/bash
#A bash script that displays numbers from 0 to 100:
	#Displays FizzBuzz when a number is a mutiple of 3 & 5
	#Displays Fizz when a number is a mutiple of 3
	#Displays Buzz when a number is a mutiple of 5
	#Otherwise display a number
	#In a list format

for ((num=1; num<=100; num++))

do
	if ((num % 3 == 0)) && ((num % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((num % 3 == 0))
	then
		echo "Fizz"
	elif ((num % 5 == 0))
	then
		echo "Buzz"
	else
		echo $num
	fi

done
