#!/usr/bin/bash
#A shell script that prints table of a given number

#input from user
echo "Enter the number "
read n

#intializing i with 1
i=1

#Looping i, i should be less or equal to 10
while [ $i -le 10 ]
do
	res=`expr $i \* $n`

	#printing on console
	echo "$n * $i = $res"

	#incrementing i by one
	((++i))
done
